#!/bin/sh

set -e

update-alternatives --install /usr/bin/astocad astocad /usr/lib/freecad/bin/freecad-python3 30 \
                    --slave /usr/bin/astocadcmd astocadcmd /usr/lib/freecad/bin/freecadcmd-python3 \
                    --slave /usr/bin/freecadcmd freecadcmd /usr/lib/freecad/bin/freecadcmd-python3 \
                    --slave /usr/bin/astocadthumbnailer astocadcmdthumbnailer /usr/lib/freecad/bin/freecad-thumbnailer \
                    --slave /usr/bin/freecadthumbnailer freecadcmdthumbnailer /usr/lib/freecad/bin/freecad-thumbnailer \
                    --slave /usr/bin/freecad freecad /usr/lib/freecad/bin/freecad-python3 \
                    --slave /usr/lib/freecad/lib freecadlib /usr/lib/freecad-python3/lib

#DEBHELPER#

exit 0
